"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.trackOpen = exports.sendEmail = exports.handleOAuthCallback = exports.generateAuthUrl = exports.performResearch = exports.generateTasks = exports.generateNotesSummary = exports.regenerateOutreach = exports.dealCoach = exports.generateEmail = exports.scoreLead = exports.onSubscriptionChange = void 0;
const admin = require("firebase-admin");
admin.initializeApp();
var billing_1 = require("./billing");
Object.defineProperty(exports, "onSubscriptionChange", { enumerable: true, get: function () { return billing_1.onSubscriptionChange; } });
var ai_1 = require("./ai");
Object.defineProperty(exports, "scoreLead", { enumerable: true, get: function () { return ai_1.scoreLead; } });
Object.defineProperty(exports, "generateEmail", { enumerable: true, get: function () { return ai_1.generateEmail; } });
Object.defineProperty(exports, "dealCoach", { enumerable: true, get: function () { return ai_1.dealCoach; } });
Object.defineProperty(exports, "regenerateOutreach", { enumerable: true, get: function () { return ai_1.regenerateOutreach; } });
Object.defineProperty(exports, "generateNotesSummary", { enumerable: true, get: function () { return ai_1.generateNotesSummary; } });
Object.defineProperty(exports, "generateTasks", { enumerable: true, get: function () { return ai_1.generateTasks; } });
var research_1 = require("./research");
Object.defineProperty(exports, "performResearch", { enumerable: true, get: function () { return research_1.performResearch; } });
var gmail_1 = require("./gmail");
Object.defineProperty(exports, "generateAuthUrl", { enumerable: true, get: function () { return gmail_1.generateAuthUrl; } });
Object.defineProperty(exports, "handleOAuthCallback", { enumerable: true, get: function () { return gmail_1.handleOAuthCallback; } });
Object.defineProperty(exports, "sendEmail", { enumerable: true, get: function () { return gmail_1.sendEmail; } });
var analytics_1 = require("./analytics");
Object.defineProperty(exports, "trackOpen", { enumerable: true, get: function () { return analytics_1.trackOpen; } });
//# sourceMappingURL=index.js.map